### ISSUE TITLE
what is the datasets you use?that is what the name of your video?

### ISSUE THREAD

**Issue by liiiiiiiiil** [loscheris/VideoCaptioning_att#1]

**Comment by loscheris** [comment]
I used the MSVD dataset, which can be found here: http://www.cs.utexas.edu/users/ml/clamp/videoDescription/

**Comment by liiiiiiiiil** [comment]
thank you,I read the code and I really don't know the line "padding_lstm2=tf.zeros([self.batch_size,2*self.dim_hidden])".why 2*self.dim_hidden?

**Comment by loscheris** [comment]
As it can be seen in https://github.com/loscheris/VideoCaptioning_att/blob/master/model_RGB.py/#L108 , at the decoding stage, the input of LSTM2 is concat(current_embed, context, output1). Both current_embed and context are in the dimension of batch_size\*hidden_dim, therefore, at the encoding stage, LSTM2 has to be padded with 2\*hidden_dim.
